// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"gorm.io/gorm"
	"gochicoba/handler"
	"gochicoba/repository"
	"gochicoba/service"
)

// Injectors from wire.go:

func ItemHandler(db *gorm.DB) handler.ItemHandler {
	itemRepository := repository.NewItemRepository(db)
	itemService := service.NewItemService(itemRepository)
	itemHandler := handler.NewItemHandler(itemService)
	return itemHandler
}
