// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-redis/redis"
	"gochicoba/handler"
	"gochicoba/producer"
	"gochicoba/repository"
	"gochicoba/service"
	"gorm.io/gorm"
)

import (
	_ "gochicoba/docs"
)

// Injectors from wire.go:

func ItemHandler(db *gorm.DB, redis2 *redis.Client) handler.ItemHandler {
	itemRepository := repository.NewItemRepository(db, redis2)
	itemService := service.NewItemService(itemRepository)
	itemHandler := handler.NewItemHandler(itemService)
	return itemHandler
}

func UserHandler(db *gorm.DB) handler.UserHandler {
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	return userHandler
}

func BuyHandler(db *gorm.DB, redis2 *redis.Client, mb *producer.MessageBroker) handler.BuyHandler {
	buyRepository := repository.NewBuyRepository(db, mb)
	buyService := service.NewBuyService(buyRepository)
	itemRepository := repository.NewItemRepository(db, redis2)
	itemService := service.NewItemService(itemRepository)
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	buyHandler := handler.NewBuyHandler(buyService, itemService, userService)
	return buyHandler
}

func LoginHandler(db *gorm.DB) handler.LoginHandler {
	loginRepository := repository.NewLoginRepository(db)
	loginService := service.NewLoginService(loginRepository)
	loginHandler := handler.NewLoginHandler(loginService)
	return loginHandler
}
