basePath: /
definitions:
  helpers.Response:
    properties:
      count: {}
      data: {}
      error: {}
      message: {}
      statusCode:
        type: integer
      total: {}
    type: object
  models.Credentials:
    properties:
      password:
        example: dummy
        type: string
      username:
        example: dummy
        type: string
    type: object
host: localhost:8081
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Bucketeer server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /items/:
    get:
      description: get items
      parameters:
      - description: page to show
        in: query
        name: page
        type: integer
      - description: limit view items
        in: query
        name: view
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Show all data Items
      tags:
      - ITEM
  /login:
    post:
      consumes:
      - application/json
      description: |-
        Login first for authorization (Bearer Authorization)
        Copy token value, then add to field authorization with format
        Example :
        Bearer ABCDEFGHIJKLMN.1234567890.XXX
      parameters:
      - description: Login
        in: body
        name: note
        required: true
        schema:
          $ref: '#/definitions/models.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.Response'
      summary: For Login to API
      tags:
      - LOGIN
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
